#  Regresión linal en Python

## El paquete scikit-learn para regresión lineal y selección de rasgos

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("C:/Users/Megaport/Desktop/python/datos machine learning/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [4]:
X = data[feature_cols]
Y = data["Sales"]

In [6]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step = 1)
selector = selector.fit(X, Y)

In [7]:
selector.support_

array([ True,  True, False])

In [8]:
selector.ranking_

array([1, 1, 2])

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
X_pred = X[["TV", "Radio"]]

In [11]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
lm.intercept_

2.921099912405138

In [13]:
lm.coef_

array([0.04575482, 0.18799423])

In [14]:
lm.score(X_pred, Y)

0.8971942610828956