# Cómo trabajar con matrices

In [1]:
import tensorflow as tf
session = tf.Session()

## 1. Cómo crear matrices

In [22]:
identity = tf.diag([1.,1.,1.,1.])
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
A = tf.truncated_normal([3,4])
print(session.run(A))

[[ 0.05988906  0.2995626   0.10178139 -0.06683255]
 [-0.5365283  -0.08662734  1.1356523   0.6725444 ]
 [ 0.08891995  0.61007124 -0.9388424  -0.5438467 ]]


In [16]:
B = tf.fill([3,4], 1998.)
print(session.run(B))

[[1998. 1998. 1998. 1998.]
 [1998. 1998. 1998. 1998.]
 [1998. 1998. 1998. 1998.]]


In [14]:
C = tf.random_uniform([4,3])
print(session.run(C))

[[0.82250583 0.52378106 0.85798657]
 [0.6978015  0.5377128  0.87457097]
 [0.8017925  0.16862774 0.7122164 ]
 [0.8195206  0.26692927 0.7921016 ]]


In [9]:
import numpy as np
data = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar con matrices

In [17]:
print(session.run(A+B))

[[1997.803  1997.0276 1997.6293 1998.4528]
 [1999.9346 1997.8871 1996.7246 1997.4604]
 [1998.0796 1998.8772 1998.1641 1996.3694]]


In [18]:
print(session.run(B-B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
print(session.run(tf.matmul(A,C))) #Multiplicación de matrices

[[ 2.0957785   2.471104    0.6220422 ]
 [-1.3202809  -1.7348678  -0.07629025]
 [-0.9680356   0.6345491  -0.38241246]]


In [23]:
print(session.run(tf.matmul(A, identity)))

[[-1.4758481  -0.41078517  1.4495059  -0.48014337]
 [-0.6704368  -0.65612847  0.00831523  0.3548104 ]
 [-0.25585264  1.0430727   0.7373843   0.65321994]]


## 3. Transpuesta y determinante, inversa


In [24]:
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [25]:
print(session.run(tf.transpose(A)))

[[-0.19331245 -1.3964337  -0.10259854]
 [ 0.06115042  1.7149265  -0.85396177]
 [ 0.19615301 -0.29483947 -0.9241324 ]
 [-0.40027288  0.7298555   0.27549264]]


In [29]:
E = tf.convert_to_tensor(np.array([[1.,2.,3.],[-3.,-6.,-1.],[0.,5.,-3]]))
print(session.run(tf.matrix_determinant(E)))

-40.0


In [30]:
print(session.run(tf.matrix_inverse(E)))

[[-0.575 -0.525 -0.4  ]
 [ 0.225  0.075  0.2  ]
 [ 0.375  0.125  0.   ]]


## 4. Descomposición

In [31]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Valores y vectores propios

In [33]:
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.24888536  -0.66882335   2.91770871]


In [34]:
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))
